
version: 0.2

phases:
    install:
        commands:
            # Yarn installation
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - sudo apt-get -y update
            - apt-get install -y yarn
    # pre_build:
        # commands:
            # Pulling the environment files from private bucket
    build:
        commands:
            # Building the react app
            - ls -la
            - cd runriot
            - yarn install
            - ls -la
            - pwd
            - npm run build
    post_build:
        commands:
            # copy the distribution to s3
            - pwd
            - ls -la
            - aws s3 cp build s3://riot.run/ --recursive

artifacts:
    base-directory: 'riotrun'
    discard-paths: yes